name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: week-3  # ✅ 모든 작업을 `week-3` 폴더에서 실행
        run: npm install

      - name: Build Application
        working-directory: week-3
        run: npm run build

      - name: Run Unit Tests
        working-directory: week-3  # ✅ week-3/src 내부에서 실행되도록 변경
        run: npm run test:unit

  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: week-3  # ✅ `week-3` 폴더에서 실행
        run: npm install

      - name: Run Unit Tests
        working-directory: week-3
        run: npm run test:unit

  integration_test:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: week-3  # ✅ `week-3` 폴더에서 실행
        run: npm install

      - name: Run Integration Tests
        working-directory: week-3
        run: npm run test:integration

  code_quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: week-3  # ✅ `week-3` 폴더에서 실행
        run: npm install

      - name: Run ESLint
        working-directory: week-3
        run: npm run lint
